### ISSUE TITLE
CasADi installation failed

### ISSUE THREAD

**Issue by Mafumaful** [zehuilu/Tutorial-on-CasADi-with-CPP#2]
Hi, I have came across this problem:
``` 
cmake -DWITH_PYTHON=ON -DWITH_IPOPT=ON -DWITH_OPENMP=ON -DWITH_THREAD=ON ..
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 9.4.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done

...

-- The following OPTIONAL packages have not been found:

 * Ipopt

-- Configuring done (1.8s)
-- Generating done (0.1s)
-- Build files have been written to: /home/miakho/env/casadi/build

```
and when I ran `make` in casadi/build an error occured:

``` 
[ 64%] Linking CXX shared library ../../../lib/libcasadi_integrator_idas.so
[ 64%] Built target casadi_integrator_idas
[ 65%] Building CXX object casadi/interfaces/sundials/CMakeFiles/casadi_rootfinder_kinsol.dir/kinsol_interface.cpp.o
[ 65%] Building CXX object casadi/interfaces/sundials/CMakeFiles/casadi_rootfinder_kinsol.dir/kinsol_interface_meta.cpp.o
[ 65%] Linking CXX shared library ../../../lib/libcasadi_rootfinder_kinsol.so
[ 65%] Built target casadi_rootfinder_kinsol
[ 65%] Building CXX object casadi/interfaces/ipopt/CMakeFiles/casadi_nlpsol_ipopt.dir/ipopt_interface.cpp.o
/home/miakho/env/casadi/casadi/interfaces/ipopt/ipopt_interface.cpp: In function ‘const char* casadi::return_status_string(Ipopt::ApplicationReturnStatus)’:
/home/miakho/env/casadi/casadi/interfaces/ipopt/ipopt_interface.cpp:412:10: error: ‘Maximum_WallTime_Exceeded’ was not declared in this scope
  412 |     case Maximum_WallTime_Exceeded:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/miakho/env/casadi/casadi/interfaces/ipopt/ipopt_interface.cpp: In member function ‘virtual int casadi::IpoptInterface::solve(void*) const’:
/home/miakho/env/casadi/casadi/interfaces/ipopt/ipopt_interface.cpp:448:17: error: ‘Maximum_WallTime_Exceeded’ was not declared in this scope
  448 |         status==Maximum_WallTime_Exceeded ||
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [casadi/interfaces/ipopt/CMakeFiles/casadi_nlpsol_ipopt.dir/build.make:76: casadi/interfaces/ipopt/CMakeFiles/casadi_nlpsol_ipopt.dir/ipopt_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1622: casadi/interfaces/ipopt/CMakeFiles/casadi_nlpsol_ipopt.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
How to solve that? Thanks :smile:

**Comment by PigBroA** [comment]
Hi @Mafumaful @zehuilu 
I got same issue, do you have any solution now?
Thanks.

**Comment by Mafumaful** [comment]
> Hi @Mafumaful @zehuilu
> I got same issue, do you have any solution now?
> Thanks.

Hi @PigBroA, 
Not yet, I skipped this.
Btw if you have solution could you tell me?
Thanks.

**Comment by zehuilu** [comment]
Hi, first I will suggest checking whether IPOPT is installed correctly. So you could run this in the console:

> sudo apt install coinor-libipopt-dev

Secondly, check the ipopt directory in your local machine. The default directory is written in my CMakeList file https://github.com/zehuilu/Tutorial-on-CasADi-with-CPP/blob/main/CMakeLists.txt#L62-L67

> set(LIBRARY_DIRS /usr/local/lib)
> if(UNIX AND NOT APPLE)
>     set(IPOPT_INCLUDE_DIRS /usr/include/coin)
> elseif(APPLE)
>     set(IPOPT_INCLUDE_DIRS /usr/local/include/coin-or)
> endif()

Make sure this directory includes ipopt. If not, you could revise it according to your path.

**Comment by zehuilu** [comment]
As for the error message related to `Maximum_WallTime_Exceeded`, I will check it on a seperate machine that has never installed this repo. I will give updates once I do that.

**Comment by PigBroA** [comment]
Hi @Mafumaful @zehuilu 

It is because of incorrect IPOPT installation as @zehuilu saying.

I followed https://coin-or.github.io/Ipopt/INSTALL.html and got solution.
(It could be fine building with HSL)

you need to download HSL on http://hsl.rl.ac.uk/ipopt
I got 2 ways to download(HSL).
1. purchase licence on https://licences.stfc.ac.uk/product/coin-hsl (academic free), and download coinhsl lib.
2. download "MA27" version lib source from HSL Archive (on https://www.hsl.rl.ac.uk/archive/index.html ), unzip them and change "src" folder name as "ma27".

The all installation procedure for IPOPT(what I did) is as follows

-------------------------------------------------------------------------------------
sudo apt update
sudo apt install gcc g++ gfortran git patch wget pkg-config liblapack-dev libmetis-dev

cd ~
mkdir lib_source
cd lib_source

git clone https://github.com/coin-or-tools/ThirdParty-ASL.git
cd ThirdParty-ASL
./get.ASL
./configure
make -j${nproc}
sudo make install

cd ~/lib_source
git clone https://github.com/coin-or-tools/ThirdParty-HSL.git
cd ThirdParty-HSL   **_<-- you must put HSL source code to here as coinhsl!!!(refer to  https://coin-or.github.io/Ipopt/INSTALL.html  )_**
![Screenshot from 2023-04-23 17-15-20](https://user-images.githubusercontent.com/98513543/233828244-f237342b-1675-4378-bb64-3c92fce37cef.png)
./configure
make -j${nproc}
sudo make install

cd ~/lib_source
git clone https://github.com/coin-or/Ipopt.git
cd Ipopt
mkdir build
cd build
../configure
make -j${nproc}
make test
sudo make install

-------------------------------------------------------------------------------------

After then, you can build CasADi with IPOPT.

Good luck.

**Comment by Mafumaful** [comment]
Hi @zehuilu @PigBroA Thank you very much! And I will try it later! 😄
